### ISSUE TITLE
TypeError: (intermediate value).resolve is not a function

### ISSUE THREAD

**Issue by Baiyuetribe** [vue-mini/vue-mini#82]
无法运行初始demo！
设备环境：mac arm64;
所有版本都为最新。

复现步骤：
```bash
bun create vue-mini@latest
bun install
bun run dev
```

报错日志：
```log
baiyue@BYdeMac-mini work % bun create vue-mini@latest

Vue Mini - 简单，强大，高性能的小程序框架

✔ 请输入项目名称： … demo_mini
✔ 是否使用 TypeScript 语法？ … 否 / 是
✔ 是否引入 Vitest 用于单元测试？ … 否 / 是
✔ 是否引入 ESLint 用于 JS 代码质量检测？ … 否 / 是
✔ 是否引入 Stylelint 用于 CSS 代码质量检测？ … 否 / 是
✔ 是否引入 Prettier 用于代码格式化？ … 否 / 是
// * 此处全部选择[否]条件
正在初始化项目 /Users/baiyue/work/demo_mini...

项目初始化完成，可执行以下命令：

  cd demo_mini
  npm install
  npm run dev

baiyue@BYdeMac-mini work % cd demo_mini 
baiyue@BYdeMac-mini demo_mini % bun install
bun install v1.1.1 (ca1dbb4e)
...
 276 packages installed [2.69s]
baiyue@BYdeMac-mini demo_mini % bun run dev
$ cross-env NODE_ENV=development node build.js
Failed to compile src/app.js
TypeError: (intermediate value).resolve is not a function
    at file:///Users/baiyue/work/demo_mini/babel.config.js:5:25
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Failed to compile src/pages/mine/index.js
TypeError: (intermediate value).resolve is not a function
    at file:///Users/baiyue/work/demo_mini/babel.config.js:5:25
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Failed to compile src/pages/home/index.js
TypeError: (intermediate value).resolve is not a function
    at file:///Users/baiyue/work/demo_mini/babel.config.js:5:25
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
启动完成，耗时：43ms
监听文件变化中...
```
界面显示
![image](https://github.com/user-attachments/assets/7ab50474-c0ff-4ac9-ba04-3094e194e164)

**Comment by yangmingshan** [comment]
你运行时用的 Node 还是 Bun？如果是 Node 那就是版本不对。

> 已安装 >= 18.19.1 < 19 或 >= 20.6.1 版本的 Node.js

以上复制至文档。

**Comment by Baiyuetribe** [comment]
ok.确实是版本问题，从18.1升级到20.15后正常
